FROM aliyunfc/fc-runtime:stretch-base

RUN mkdir -p /usr/share/man/man1
RUN apt-get update && apt-get install -y \
        openjdk-11-jdk \
        maven \
    --no-install-recommends && rm -r /var/lib/apt/lists/*